[NDD-388] webpack -> vite로 마이그레이션 (3h)
the-NDD/Gomterview-FE pull request #4
Opened 2024-01-08 13:17 UTC by milk717

# Why

빌드 속도를 향상시켜 배포와 개발 단계에서 소요되는 번들링 시간을 단축시키기 위해 webpack에서 vite로 마이그레이션을 진행했습니다.

# How

## vite로 마이그레이션 진행 과정
1. vite 프로젝트 생성 
```
yarn create vite {projectName} --template react-ts
```
위 명령어로 새로운 vite 프로젝트를 생성했습니다.
2. 파일 이동
- package.json, tsconfig, vite.config등 설정 파일을 먼저 옮긴 후 잘 실행되는지 확인했습니다.
- src 내부에 있는 파일을 옮겨서 잘 실행되는지 확인했습니다.
- 수정해야하는 코드가 있는 경우 수정했습니다.
  - webpack과 vite의 env import 방식이 다른 부분 수정
  - env 내부 변수의 이름 앞에 VITE 프리픽스를 붙임
3. vite로 마이그레이션 하는김에 yarn berry로 마이그레이션. 하지만 이는 아래 이슈로 인해 다시 롤백함  

## vite로 마이그레이션 하면서 겪은 이슈
### yarn berry에서 ffmpeg이 동작하지 않음
vite 마이그레이션을 진행하면서 yarn berry로 마이그레이션하는 작업도 함께 진행했습니다.
하지만 yarn berry에서 ffmpeg가 동작하지 않는다는 이슈가 생겨서 npm으로 다시 롤백했습니다.

### vite 사용시 ffmpeg 모듈이 로드되지 않음
ffmpeg모듈이 로드되지 않는다는 이슈가 발생했습니다.
[ffmpeg.wasm 공식문서](https://ffmpegwasm.netlify.app/docs/getting-started/usage)를 보고 vite를 사용하는 경우 ffmpeg모듈의 주소를 아래와 같이 변경해야 한다는 것을 찾아서 해결했습니다.
<img width="1034" alt="image" src="https://github.com/the-NDD/Gomterview-FE/assets/57657868/38369472-1222-4f2b-8f2d-c10956402e1b">

# Result

webpack -> vite로 번들러 마이그레이션 완료!

# Prize

> 성능 측정에 대한 부분은 블로깅 글을 작성하면서 업데이트하겠습니다.

# Reference
- [Webpack → Vite: 번들러 마이그레이션 이야기](https://engineering.ab180.co/stories/webpack-to-vite)
- [FFmpeg hangs on load and no console errors are displayed · Issue #532 · ffmpegwasm/ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm/issues/532)
- [Vite의 환경 변수와 모드 | Vite](https://ko.vitejs.dev/guide/env-and-mode.html)

2024-01-09 07:09 UTC, adultlee commented
해당 테스크에서 코드상으론 작성되지 않았지만, 기존의 yarn berry 로 연결되었던 CD 스크립트를 cloudflare에서 수정해주어야만 합니다!
반영된 이후 확인 부탁드립니다(그런데 수정이 된거 같군요!!)

<img width="488" alt="image" src="https://github.com/the-NDD/Gomterview-FE/assets/77886826/883b30f3-30df-4b42-aad4-3eb687f0dee2">


바로 merge 되어도 괜찮을것 같습니다!!

2024-01-09 07:09 UTC, adultlee approved these changes

2024-01-09 07:19 UTC, Yoon-Hae-Min commented on vite.config.js
[p-3] js 파일과 ts파일은 어떤 차이인가요?

2024-01-09 07:19 UTC, Yoon-Hae-Min commented on package.json
> -  },
[p-3] 린트 스테이지 지워진 이유가 있을까요??

2024-01-09 07:19 UTC, Yoon-Hae-Min commented on README.md
> +# React + TypeScript + Vite
[p-4] 무로 돌아가버린 README ㅋㅋㅋㅋ

2024-01-09 08:41 UTC, adultlee requested changes

2024-01-09 08:41 UTC, adultlee commented on vite.config.js
이거 문제가 있습니다!! 아주 좋은 지적이에요!! 


<img width="844" alt="image" src="https://github.com/the-NDD/Gomterview-FE/assets/77886826/006bd8a3-e2b0-4931-93e8-18b6af1a64a6">

include 옵션은 해당 dir에 대해서 ts 컴파일을 하는 위치를 의미하는데, 이렇게 되면 vite.config.ts만 적용이 됩니다. src로 수정하는게 좋아보이네요! 저는 현재 dir를 다한 예시였지만 src가 좋을것 같습니다

2024-01-09 11:03 UTC, adultlee commented on README.md
> +# React + TypeScript + Vite
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-01-11 01:29 UTC, milk717 commented on vite.config.js
f999d62d 반영완료!!

2024-01-11 01:30 UTC, milk717 commented on package.json
> -  },
06236af0 살렸어요~

2024-01-11 01:33 UTC, milk717 commented on README.md
> +# React + TypeScript + Vite
764dc9ca 복구완료!!

2024-01-11 02:10 UTC, Yoon-Hae-Min commented on src/APIErrorBoundary.js
[p-3]
![image](https://github.com/the-NDD/Gomterview-FE/assets/49224104/8990c9bf-6c82-474e-b5eb-74204602f206)

이게 다 무슨일이이죠?!?!?!

2024-01-11 02:12 UTC, Yoon-Hae-Min commented on .husky/pre-commit
[p-2] 이것도 복구해주셔야 해요!

2024-01-11 05:31 UTC, Yoon-Hae-Min commented
[p-1] 레포가 옮겨져서 husky설정을 다시 해야 하더라고요 다들 yarn setup로 git 세팅 한번씩 부탁드리겠습니다

2024-01-11 07:13 UTC, Yoon-Hae-Min approved these changes

2024-01-11 07:15 UTC, merged